version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  node-app:
    build:
      context: ./node 
    command: npm start
    environment:
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydatabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./node:/usr/src/app  

volumes:
  postgres-data:
