version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  node-app:
    build:
      context: ./node 
    command: npm start
    environment:
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydatabase
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./node:/usr/src/app  

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/.next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - node-app

volumes:
  postgres-data:
